blog/urls.py
from django.urls import path
from .views import BasePostListView, post_detail, create_new_post, update_post, delete_post, edit_comment, delete_comment, about, likes, thumbs, StoriesListView, ProgrammingListView, SpiritualityListView
from . import views


urlpatterns = [
    path('', BasePostListView.as_view(), name='blog-home'),
    path('about/', views.about, name='blog-about'),
    path('stories/', StoriesListView.as_view(), name='blog-stories'),
    path('programming/', ProgrammingListView.as_view(), name='blog-programming'),
    path('spirituality/', SpiritualityListView.as_view(), name='blog-spirituality'),
    path('<slug:slug>/', views.post_detail, name="post_detail"),
    path('create', create_new_post, name="new_post"),
    path('update_post/<slug:slug>/', views.update_post, name='update_post'),
    path('delete_post/<slug:slug>/', views.delete_post, name='delete_post'),
    path(
        '<slug:slug>/edit_comment/<int:comment_id>',
        views.edit_comment, name='edit_comment'
        ),
    path(
        '<slug:slug>/delete_comment/<int:comment_id>',
        views.delete_comment, name='delete_comment'
        ),
    path('<int:pk>/likes/', views.likes, name='like_post'),
    path('<int:pk>/thumbs/', views.thumbs, name='thumbs'),
]

restaurants/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf.urls.static import static

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('profile/', user_views.profile, name='profile'),
    path('delete/', user_views.delete_profile, name='delete'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from cloudinary.models import CloudinaryField


# likes Based on: https://www.youtube.com/watch?v=PXqRPqDjDgc
# Down and Up vote (thumbs up/ thumbs down) based on:
# https://www.youtube.com/watch?v=onZ69P9wS2o
# Based on CI walk threw
STATUS = ((0, "Draft"), (1, "Published"))


class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    CATEGORY_CHOICES = [
        ('stories', 'Short Sotires/Novellas'),
        ('programming', 'Programming Guide'),
        ('spirituality', 'Spirituality'),
        ('general', 'General'),
    ]

    featured_image = CloudinaryField(
        'post_image', default='placeholder', transformation=[{
            'width': 200,
            'height': 150,
            'crop': "fill",
            'effect': "sharpen:200"
            },
        ])
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.TextField(blank=True)
    likes = models.ManyToManyField(User, related_name='blog_post', blank=True)
    thumbsup = models.IntegerField(default=0)
    thumbsdown = models.IntegerField(default=0)
    thumbs = models.ManyToManyField(
        User, related_name='thumbs', default=None, blank=True
        )

    category = models.CharField(
        max_length=20, 
        choices=CATEGORY_CHOICES,
        default='general'
    )
    

    def save(self, *args, **kwargs):
        if not self.slug or self.title_changed():
            self.slug = self.generate_slug()
        super().save(*args, **kwargs)

    def title_changed(self):
        if self.pk:
            old_post = Post.objects.get(pk=self.pk)
            return self.title != old_post.title
        return False

    def generate_slug(self):
        return slugify(self.title)

    def update_slug(self):
        """
        Updates the slug based on the current title.
        """
        self.slug = self.generate_slug()
        self.save(update_fields=['slug'])

    def total_likes(self):
        return self.likes.count()

# Based on: https://www.youtube.com/watch?v=onZ69P9wS2o
class Vote(models.Model):
    post = models.ForeignKey(
        Post, related_name='postid',
        on_delete=models.CASCADE,
        default=None, blank=True
        )
    user = models.ForeignKey(
        User, related_name='userid',
        on_delete=models.CASCADE,
        default=None,
        blank=True
        )
    vote = models.BooleanField(default=True)


# Based on Post model
class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        related_name='comments',
        on_delete=models.CASCADE
        )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='commenter'
        )
    body = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    approved = models.BooleanField(default=False)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment {self.body} by {self.author}"

    class Meta:
        ordering = ["-date_posted"]

blog/forms.py
from django import forms
from .models import Post, Comment
from django_summernote.widgets import SummernoteWidget



class CreateNewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'category',
            #'slug',
            'content',
            'excerpt',
            'featured_image',
            'status'
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'excerpt': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'content': SummernoteWidget(),
            'status': forms.Select(attrs={'class': 'form-control'}),
            }

    def __init__(self, *args, **kwargs):
        super(CreateNewPostForm, self).__init__(*args, **kwargs)
        if 'slug' in self.fields:
            del self.fields['slug']

    def save(self, commit=True):
        instance = super(CreateNewPostForm, self).save(commit=False)
        if commit:
            instance.save()
            if self.cleaned_data['featured_image']:
                instance.featured_image = self.cleaned_data['featured_image']
                instance.save()
        return instance


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'category',
            #'slug',
            'content',
            'excerpt',
            'featured_image',
            'status'
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'excerpt': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'content': SummernoteWidget(),
            'status': forms.Select(attrs={'class': 'form-control'}),
            }

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.update_slug()
        if commit:
            instance.save()
        return instance


# Based on Djangocentral:
# https://djangocentral.com/creating-comments-system-with-django/
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse
from django.views.generic import ListView
from .forms import CreateNewPostForm, PostUpdateForm, CommentForm
from django.contrib import messages
from .models import Post, Comment, Vote

from django.http import JsonResponse
from django.db.models import F


# Tutorial based
def home(request):
    context = {"posts": Post.objects.all()}
    return render(request, "blog/home.html", context)


# Tutorial video 10 - 9:00min.
class BasePostListView(ListView):
    model = Post
    template_name = "blog/home.html"
    context_object_name = "posts"
    ordering = ["-date_posted"]
    paginate_by = 6
    category = None

    def get_queryset(self):
        queryset = super().get_queryset()
        # Only show published posts
        queryset = queryset.filter(status=1)
        if self.category:
            queryset = queryset.filter(category=self.category)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_category'] = self.category
        context['page_title'] = self.get_page_title()
        return context
    
    def get_page_title(self):
        title_map = {
            'stories': 'Short Stories & Novellas',
            'programming': 'Programming Guides',
            'spirituality': 'Spirituality',
            None: 'All Posts'
        }
        return title_map.get(self.category, 'All Posts')


# Create Slugs based on simple.rocks:
# https://simpleit.rocks/python/django/
# generating-slugs-automatically-in-django-easy-solid-approaches/
# Implementing comments based on djangocentral:
# https://djangocentral.com/creating-comments-system-with-django/
# Total Likes based on: https://www.youtube.com/watch?v=PXqRPqDjDgc
# Based on CI Django Walkthrew post_detail view:
def post_detail(request, slug):
    """
    Display an individual :model:`blog.Post`.

    **Context**

    ``post``
    An instance of :model:`blog.Post`.

    **Template:**

    :template:`blog/post_detail.html`
    """

    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.all().order_by("-date_posted")
    comment_count = post.comments.filter(approved=True).count()
    total_likes_count = post.total_likes()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Comment submitted and awaiting approval",
            )
        else:
            return render(
                request,
                "blog/post_detail.html",
                {
                    "post": post,
                    "comments": comments,
                    "comment_count": comment_count,
                    "total_likes_count": total_likes_count,
                    "comment_form": comment_form,
                },
            )

    # If it's not a POST request or the form is valid,
    # create a new unbound form
    comment_form = CommentForm()

    return render(
        request,
        "blog/post_detail.html",
        {
            "post": post,
            "comments": comments,
            "comment_count": comment_count,
            "total_likes_count": total_likes_count,
            "comment_form": comment_form,
        },
    )


# Based users/views.py profile
@login_required
def create_new_post(request):
    if request.method == "POST":
        post_form = CreateNewPostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, "Your post was successfully submitted!")
            return redirect("blog-home")
        else:
            messages.error(
                request,
                "There was an error submitting your post." +
                " Please check the form and try again.",
            )
    else:
        post_form = CreateNewPostForm()

    context = {"post_form": post_form}
    return render(request, "blog/create.html", context)


@login_required
def update_post(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.user != post.author:
        messages.error(request, "You are not authorized to edit this post.")
        return redirect("post-detail", slug=slug)

    if request.method == "POST":
        post_form = PostUpdateForm(request.POST, request.FILES, instance=post)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.update_slug()
            post.save()
            messages.success(request, "Post updated successfully.")
            return redirect("post_detail", slug=post.slug)
        else:
            messages.error(
                request,
                "There was an error updating your post." +
                " Please check the form and try again.",
            )
    else:
        post_form = PostUpdateForm(instance=post)

    context = {"post_form": post_form, "slug": slug}
    return render(request, "blog/update_post.html", context)


# Based on update_post view
@login_required
def delete_post(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.user != post.author:
        messages.error(request, "You are not authorized to delete this post!")
    else:
        post.delete()
        messages.success(request, "Post deleted successfully!")

    return redirect("blog-home")


@login_required
def edit_comment(request, comment_id, slug):
    post = get_object_or_404(Post, slug=slug)
    comments = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST, instance=comments)
        if not comment_form.is_valid():
            context = {
                "comment_form": comment_form,
                "post": post,
                "comments": [comments],
            }
            return render(
                request, "blog/post_detail.html", context
            )  # Render with errors
        else:
            if comments.author != request.user:
                return HttpResponseForbidden(
                    "You are not authorized to edit this comment."
                )
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, "Comment Updated!")
            return HttpResponseRedirect(
                reverse("post_detail", args=[slug])
            )  # Redirect on success


# Based on CI walk threw
@login_required
def delete_comment(request, slug, comment_id):
    if request.method == "POST":
        post = get_object_or_404(Post, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        if request.user == comment.author:
            comment.delete()
            messages.success(request, "Comment deleted successfully!")
        else:
            messages.error(request, "You can only delete your own comments!")
            return HttpResponseRedirect(
                reverse("login")
                + "?next="
                + reverse("delete_comment", args=[post.slug, comment.id])
            )
    else:
        messages.error(request, "Invalid request method!")

    return HttpResponseRedirect(reverse("post_detail", args=[slug]))


# Based on tutorial: https://www.youtube.com/watch?v=PXqRPqDjDgc
@login_required
def likes(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        if request.user.is_authenticated:
            if request.user in post.likes.all():
                post.likes.remove(request.user)
            else:
                post.likes.add(request.user)
        else:
            messages.error(request, "You need to log in to like posts.")

    return redirect("blog-home")


# Based on tutorial: https://www.youtube.com/watch?v=onZ69P9wS2o
@login_required
def thumbs(request, pk):
    if request.method == "POST" and request.POST.get("action") == "thumbs":
        id = pk
        button = request.POST.get("button")
        update = get_object_or_404(Post, pk=id)

        # Check if user already voted
        user_vote = Vote.objects.filter(
            post_id=id, user_id=request.user.id
        ).first()

        if not user_vote:
            # User hasn't voted before
            if button == "thumbsup":
                update.thumbsup = F("thumbsup") + 1
                new_vote = Vote(
                    post_id=id, user_id=request.user.id, vote=True
                    )
                new_vote.save()
            else:
                update.thumbsdown = F("thumbsdown") + 1
                new_vote = Vote(
                    post_id=id, user_id=request.user.id, vote=False
                )
                new_vote.save()
        else:  # User has already voted
            if button == "thumbsup" and user_vote.vote:
                # Upvoted and clicks upvote again --> remove vote
                update.thumbsup = F("thumbsup") - 1
                user_vote.delete()
            elif button == "thumbsdown" and not user_vote.vote:
                # Downvoted and clicks downvote again --> remove vote
                update.thumbsdown = F("thumbsdown") - 1
                user_vote.delete()
            else:
                # User voted with a different value before --> change vote
                user_vote.vote = not user_vote.vote  # Flip the vote value

blog/templates/blog/about.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12 card mb-4  mt-3 left  top">
      <div class="card-body">
          <h1><u>About Us:</u></h1>
          <p class="card-text">Welcome to Restaurant-Review-Blog, your go-to destination for vibrant dining experiences!</p>

            <p class="card-text">Restaurant-Review-Blog is designed with a singular purpose: to enable users to share their unique dining adventures and insights with a global audience. Here, users can meticulously document their restaurant visits, capturing the essence of every dining experience, from the exquisite flavors to the ambiance that makes each visit memorable.</p>
            
            <p class="card-text">Our platform fosters a vibrant community where food enthusiasts can engage in meaningful discussions. Users can leave comments, share their reviews, and express their opinions through simple thumbs-up or thumbs-down gestures. This interactive environment encourages a rich exchange of ideas and perspectives, making every visit to Restaurant-Review-Blog a unique culinary adventure.</p>
            
            <p class="card-text">But the journey doesn't end there! Users have the option to mark their favorite posts, ensuring that unforgettable dining experiences are always within easy reach. This feature is a testament to our commitment to enhancing the user experience and making the most cherished dining memories easily accessible.</p>
            
            <p class="card-text">At Restaurant-Review-Blog, we are dedicated to providing users with a comprehensive overview of the dining scene. Our mission is to empower users to make informed dining decisions by offering a wealth of information and insights from fellow food lovers. Whether you're seeking culinary inspiration, sharing your latest gastronomic discoveries, or simply looking for a place to express your love for great food and experiences, Restaurant-Review-Blog is your ultimate companion on the culinary journey.</p>
      </div>
      <br>
      <hr>
      <div class="card-body">
        <h1><u>Contact Us!</u></h1>
        <p class="card-text">Reach out to us to statisfy your needs!</p>
        <hr>
        <p class="card-text">Call our Hotline: <b>062 842 510 474</b></p>
        <p class="card-text">Write us an E-Mail: <b>info@restaurant-blog.com</b></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <!-- Header Section -->
      <div class="create-header text-center mb-5">
        <h1 class="display-4 text-white mb-3">Create New Post</h1>
        <p class="lead text-light">Share your thoughts, stories, or guides with the community</p>
      </div>

      <!-- Form Container -->
      <div class="card shadow-lg border-0">
        <div class="card-body p-5">
          {% if user.is_authenticated %}
          <!-- Quick Start Options -->
          <div class="quick-start-options text-center mb-4" id="quick-start">
            <h4 class="mb-4">What would you like to write about?</h4>
            <div class="row">
              <div class="col-md-4 mb-3">
                <button class="btn btn-outline-primary btn-lg w-100 h-100 category-btn" data-category="stories">
                  <i class="fas fa-book fa-2x mb-2"></i>
                  <h5>Short Story</h5>
                  <small class="text-muted">Share a creative story</small>
                </button>
              </div>
              <div class="col-md-4 mb-3">
                <button class="btn btn-outline-success btn-lg w-100 h-100 category-btn" data-category="programming">
                  <i class="fas fa-code fa-2x mb-2"></i>
                  <h5>Programming Guide</h5>
                  <small class="text-muted">Teach something technical</small>
                </button>
              </div>
              <div class="col-md-4 mb-3">
                <button class="btn btn-outline-warning btn-lg w-100 h-100 category-btn" data-category="spirituality">
                  <i class="fas fa-spa fa-2x mb-2"></i>
                  <h5>Spiritual Insight</h5>
                  <small class="text-muted">Share wisdom and reflections</small>
                </button>
              </div>
            </div>
            <div class="mt-4">
              <button class="btn btn-secondary" id="skip-category-btn">
                <i class="fas fa-arrow-right mr-2"></i>Skip to form
              </button>
            </div>
          </div>

          <!-- Main Form -->
          <div id="post-form-container" style="display: none;">
            <div class="form-header d-flex justify-content-between align-items-center mb-4">
              <h3 class="mb-0">Create Your Post</h3>
              <button type="button" class="btn btn-outline-secondary" id="back-to-categories">
                <i class="fas fa-arrow-left mr-2"></i>Change Category
              </button>
            </div>

            <form method="post" enctype="multipart/form-data" id="post-form">
              {% csrf_token %}

              <!-- Category Preview -->
              <div class="category-preview alert alert-info mb-4" id="category-preview" style="display: none;">
                <i class="fas fa-tag mr-2"></i>
                <strong>Category:</strong> <span id="selected-category"></span>
              </div>

              <div class="row">
                <div class="col-md-8">
                  {{ post_form.title|as_crispy_field }}
                </div>
                <div class="col-md-4">
                  {{ post_form.category|as_crispy_field }}
                </div>
              </div>

              {{ post_form.excerpt|as_crispy_field }}

              <!-- Featured Image Upload with Preview -->
              <div class="form-group">
                <label for="featured_image">Featured Image</label>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="id_featured_image" name="featured_image" accept="image/*">
                  <label class="custom-file-label" for="featured_image">Choose image...</label>
                </div>
                <small class="form-text text-muted">
                  Recommended size: 1200x600px. This will be the main image for your post.
                </small>
                <div class="image-preview mt-2" id="image-preview" style="display: none;">
                  <img id="preview-img" class="img-fluid rounded" style="max-height: 200px;">
                  <button type="button" class="btn btn-sm btn-outline-danger mt-2" id="remove-image">
                    <i class="fas fa-times mr-1"></i>Remove Image
                  </button>
                </div>
              </div>

              <!-- Content Editor -->
              <div class="form-group">
                <label for="id_content">Content</label>
                <div class="editor-info mb-2">
                  <small class="text-muted">
                    <i class="fas fa-info-circle mr-1"></i>
                    Use the toolbar above for formatting. You can add images, links, and more.
                  </small>
                </div>
                {{ post_form.content }}
              </div>

              <!-- Status and Actions -->
              <div class="row">
                <div class="col-md-6">
                  {{ post_form.status|as_crispy_field }}
                </div>
                <div class="col-md-6 text-right">
                  <div class="btn-group mt-4">
                    <!--<button type="button" class="btn btn-outline-secondary" id="preview-post">
                      <i class="fas fa-eye mr-2"></i>Preview
                    </button>-->
                    <button type="submit" class="btn btn-primary">
                      <i class="fas fa-paper-plane mr-2"></i>Publish Post
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
          {% else %}
          <!-- Not Authenticated Message -->
          <div class="text-center py-5">
            <i class="fas fa-lock fa-3x text-muted mb-3"></i>
            <h3>Authentication Required</h3>
            <p class="text-muted">You need to be logged in to create a post.</p>
            <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-primary mr-2">
              <i class="fas fa-sign-in-alt mr-2"></i>Login
            </a>
            <a href="{% url 'register' %}" class="btn btn-outline-primary">
              <i class="fas fa-user-plus mr-2"></i>Register
            </a>
          </div>
          {% endif %}
        </div>
      </div>

      <!-- Tips Section -->
      <div class="card mt-4 border-0 bg-light">
        <div class="card-body">
          <h5><i class="fas fa-lightbulb text-warning mr-2"></i>Writing Tips</h5>
          <ul class="list-unstyled mb-0">
            <li><i class="fas fa-check text-success mr-2"></i> Write a compelling title that grabs attention</li>
            <li><i class="fas fa-check text-success mr-2"></i> Use the excerpt to summarize your post</li>
            <li><i class="fas fa-check text-success mr-2"></i> Add relevant images to make your post engaging</li>
            <li><i class="fas fa-check text-success mr-2"></i> Use headings and formatting to improve readability</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--Likes-->
    <form class="like-form" action="{% url 'like_post' pk=pk %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Like</button>
        <!--Display Total Likes-->
        <span class="total-likes-count">{{ total_likes_count }}</span>
    </form>
  {% endblock content %}

blog/templates/blog/update_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div id="edit-form-container">
                {% if user.is_authenticated %}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ post_form|crispy }}
                    <button class="btn btn-success" type="submit">Update</button>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}